### PR TITLE
Identity filtering: avoid infinite recursion properly

### LINKED ISSUE #497: Installing custom certificate to Keychain causes santactl binary to throw bus error
I have a package that installs custom root/intermediate certificates for my internal PKI infrastructure. Nothing complex here. 

There are two certificates in this package that if installed will break Santa.
`security add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" "/path/to/root.cer"`

In stdout I see error messages like:

- `Bus error: 10` if I run from a root shell
or
- `zsh: bus error sudo santactl sync` if I run from a regular admin shell

Nothing obvious in `/var/db/santa/santa.log` jumps out at me.

### PR DESCRIPTION
**Pull request by russellhancox**
I believe this will fix google/santa#497.

### CODE REVIEW

File: Source/MOLAuthenticatingURLSession/MOLAuthenticatingURLSession.m [hunk 1]
```diff
@@ -371,10 +371,10 @@ - (SecIdentityRef)identityByFilteringArray:(NSArray *)array
       return identityRef;
     } else {
       // Avoid infinite recursion from self-signed certs
-      if ((cert.commonName && [cert.commonName isEqual:cert.issuerCommonName]) &&
-          (cert.countryName && [cert.countryName isEqual:cert.issuerCountryName]) &&
-          (cert.orgName && [cert.orgName isEqual:cert.issuerOrgName]) &&
-          (cert.orgUnit && [cert.orgUnit isEqual:cert.issuerOrgUnit])) {
+      if ((!cert.commonName || [cert.commonName isEqual:cert.issuerCommonName]) &&
```
Comment (tburgin) [inline Source/MOLAuthenticatingURLSession/MOLAuthenticatingURLSession.m:374]: I think the `isEqual:` usage is intentional here (vs. `isEqualToString:`), but maybe add a note for future readers.

**Review by tburgin — APPROVED** [review]

File: Source/MOLAuthenticatingURLSession/MOLAuthenticatingURLSession.m (hunk 1 above)
Comment (russellhancox) [reply Source/MOLAuthenticatingURLSession/MOLAuthenticatingURLSession.m:374]: I can't remember what the reason was, if there is one, other than there not being any real advantage to `isEqualToString:`
